// packages/app-preact/src/App.tsx
/** @jsxImportSource preact */
import { createRendererDemoContract, formatRendererDemo } from '@cheshirecode/demo-contract';
import { copyToClipboard } from '@cheshirecode/browser-clipboard';
import { memo } from 'preact/compat';

const contract = createRendererDemoContract('Preact');

const CompatBadge = memo(() => <span data-testid="compat">preact-compat</span>);

export function App() {
  return (
    <>
      <a href="/" className="back-link" style={{ color: 'inherit', textDecoration: 'none', display: 'inline-block', marginBottom: 16, fontSize: 13 }}>← Back to showcase</a>
      <main>
        <h1>{contract.title}</h1>
        <p>{formatRendererDemo(contract)}</p>
        <p>{contract.url}</p>
        <CompatBadge />
        <button type="button" onClick={() => copyToClipboard(contract.slug)}>
          copy
        </button>
      </main>
    </>
  );
}

// packages/app-solidjs/src/App.tsx
import { createRendererDemoContract, formatRendererDemo } from '@cheshirecode/demo-contract';
import type { Component } from 'solid-js';

const contract = createRendererDemoContract('SolidJS');

export const App: Component = () => (
  <div>
    <a href="/" class="back-link" style={{ color: 'inherit', 'text-decoration': 'none', display: 'inline-block', 'margin-bottom': '16px', 'font-size': '13px' }}>← Back to showcase</a>
    <main>
      <h1>{contract.title}</h1>
      <p>{formatRendererDemo(contract)}</p>
      <p>{contract.url}</p>
    </main>
  </div>
);
